# Generated by Django 4.2 on 2024-10-01 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=100, verbose_name="email")),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        help_text="Введите фамилию",
                        max_length=150,
                        null=True,
                        verbose_name="Фамилия",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        help_text="Введите имя",
                        max_length=150,
                        null=True,
                        verbose_name="Имя",
                    ),
                ),
                (
                    "patronymic",
                    models.CharField(
                        blank=True,
                        help_text="Введите отчество",
                        max_length=150,
                        null=True,
                        verbose_name="Отчество",
                    ),
                ),
                (
                    "a_comment",
                    models.TextField(
                        blank=True,
                        help_text="Введите комментарий",
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True,
                        help_text="Введите дату рождения",
                        null=True,
                        verbose_name="Дата рождения",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
                "ordering": ["last_name", "first_name", "patronymic", "date_of_birth"],
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mailing_name",
                    models.CharField(
                        help_text="Укажите название рассылки",
                        max_length=150,
                        verbose_name="Название рассылки",
                    ),
                ),
                (
                    "datetime_first_mailing",
                    models.DateTimeField(verbose_name="Дата и время отправки рассылки"),
                ),
                (
                    "next_datetime_mailing",
                    models.DateTimeField(
                        verbose_name="Дата и время следующей отправки рассылки"
                    ),
                ),
                (
                    "last_datetime_mailing",
                    models.DateTimeField(
                        verbose_name="Дата и время последней отправки рассылки"
                    ),
                ),
                (
                    "period_mailing",
                    models.IntegerField(
                        choices=[
                            (1, "Каждую минуту"),
                            (60, "Каждый час"),
                            (1440, "Ежедневно"),
                            (10080, "Еженедельно"),
                            (43200, "Ежемесячно(каждые 30 дней)"),
                        ],
                        help_text="Выберите период рассылки",
                        verbose_name="Период рассылки",
                    ),
                ),
                (
                    "mailing_status",
                    models.IntegerField(
                        choices=[
                            (0, "Создана"),
                            (1, "Запущена"),
                            (2, "Отменена"),
                            (3, "Завершена"),
                        ],
                        help_text="Выберите статус рассылки",
                        verbose_name="Статус рассылки",
                    ),
                ),
                (
                    "clients",
                    models.ManyToManyField(
                        related_name="settings_client",
                        to="mailing.client",
                        verbose_name="Клиенты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ["owner", "mailing_status", "next_datetime_mailing"],
                "permissions": [
                    ("can_edit_mailing_status", "Может отключать рассылки")
                ],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "letter_subject",
                    models.CharField(
                        help_text="Укажите тему письма",
                        max_length=255,
                        verbose_name="Тема письма",
                    ),
                ),
                (
                    "image_message",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение письма",
                        null=True,
                        upload_to="mailings/images",
                        verbose_name="Изображение письма",
                    ),
                ),
                (
                    "letter_body",
                    models.TextField(
                        help_text="Введите текст письма", verbose_name="Тело письма"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение рассылки",
                "verbose_name_plural": "Сообщения рассылки",
            },
        ),
        migrations.CreateModel(
            name="MailingAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datetime_attempt",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время попытки отправки"
                    ),
                ),
                (
                    "attempt_status",
                    models.BooleanField(editable=False, verbose_name="Статус попытки"),
                ),
                (
                    "service_response",
                    models.TextField(
                        editable=False, null=True, verbose_name="Ответ сервиса"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailing.client",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailing.mailing",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка отправки письма",
                "verbose_name_plural": "Попытки отправки письма",
            },
        ),
        migrations.AddField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settings_message",
                to="mailing.message",
                verbose_name="Сообщение рассылки",
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
