# Generated by Django 4.2 on 2024-10-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="next_datetime_mailing",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Дата и время следующей отправки рассылки",
            ),
        ),
    ]
