# Generated by Django 4.2 on 2024-10-04 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_alter_mailing_next_datetime_mailing"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["owner", "mailing_status", "next_datetime_mailing"],
                "permissions": [
                    ("can_disable_mailing_status", "Может отключать рассылки")
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
