# Generated by Django 4.2 on 2024-10-17 10:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mailing", "0003_alter_mailing_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="owner",
        ),
        migrations.AddField(
            model_name="client",
            name="owner",
            field=models.ManyToManyField(
                related_name="clients",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
