# Generated by Django 4.2 on 2024-10-24 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0004_remove_client_owner_client_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailingattempt",
            name="client",
        ),
    ]
