[tool.poetry]
name = "owl-postal-service"
version = "0.1.0"
description = ""
authors = ["maxim"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
