# Generated by Django 4.2 on 2024-10-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(
                help_text="Введите заголовок статьи",
                max_length=100,
                verbose_name="Заголовок",
            ),
        ),
    ]
